apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: codeflare-stack-config
  envs:
    - params.env
configurations:
  - params.yaml

vars:
  - name: namespace
    objref:
      kind: ConfigMap
      name: codeflare-stack-config
      apiVersion: v1
    fieldref:
      fieldpath: data.namespace
  - name: INSTASCALE_CPU_LIMIT
    objref:
      kind: ConfigMap
      name: codeflare-stack-config
      apiVersion: v1
    fieldref:
      fieldpath: data.INSTASCALE_CPU_LIMIT
  #- name: INSTASCALE_CPU_REQUEST
    #objref:
      #kind: ConfigMap
      #name: codeflare-stack-config
      #apiVersion: v1
    #fieldref:
      #fieldpath: data.INSTASCALE_CPU_REQUEST
  #- name: INSTASCALE_MEMORY_LIMIT
  #  objref:
  #    kind: ConfigMap
  #    name: codeflare-stack-config
  #    apiVersion: v1
  #  fieldref:
  #    fieldpath: data.INSTASCALE_MEMORY_LIMIT
  #- name: INSTASCALE_MEMORY_REQUEST
  #  objref:
  #    kind: ConfigMap
  #    name: codeflare-stack-config
  #    apiVersion: v1
  #  fieldref:
  #    fieldpath: data.INSTASCALE_MEMORY_REQUEST
resources:
- codeflare-notebook-imagestream.yaml
- instascale.yaml
- mcad.yaml
- ../rbac
