varReference:
  - path: data
    kind: ConfigMap
  - path: subjects[]/namespace
    kind: ClusterRoleBinding
  - path: spec/controllerResources/limits/cpu
    kind: InstaScale
  - path: spec/controllerResources/requests/cpu
    kind: InstaScale
  - path: spec/controllerResources/limits/memory
    kind: InstaScale
  - path: spec/controllerResources/requests/memory
    kind: InstaScale
  - path: spec/controllerResources/limits/cpu
    kind: MCAD
  - path: spec/controllerResources/requests/cpu
    kind: MCAD
  - path: spec/controllerResources/limits/memory
    kind: MCAD
  - path: spec/controllerResources/requests/memory
    kind: MCAD

