varReference:
  - path: data
    kind: ConfigMap
  - path: subjects[]/namespace
    kind: ClusterRoleBinding
  - path: spec/controllerResources/limits/cpu
    kind: InstaScale
  - path: spec/controllerResources/request/cpu
    kind: InstaScale
  - path: spec/controllerResources/limits/memory
    kind: InstaScale
  - path: spec/controllerResources/request/memory
    kind: InstaScale
